### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#283]
Hi,
I have a problem I cannot figured out at the moment, and I'm not sure it is a Caliburn Micro issue.
I developed an UWP application on my laptop, compiling and running fine. Then I had a new laptop, so I transfered the project. It build correctly, but at run time I got the exception below. Then I attached the Caliburn project in my solution to try to see what was wrong.
I also reinstalled Visual Studio,in case the installation was broken but it didn't help.
I've attached the screenshot. Any hints would be appreciated :) Thank you

Additional information: Method not found: 'Void Windows.Foundation.Metadata.ComposableAttribute..ctor(System.Type, Windows.Foundation.Metadata.CompositionType, UInt32, System.String)'.

In the CM logs, I got this :

ERROR:[2016-01-12T10:33:59.3743574+01:00] System.MissingMethodException: Method not found: 'Void Windows.Foundation.Metadata.ComposableAttribute..ctor(System.Type, Windows.Foundation.Metadata.CompositionType, UInt32, System.String)'.
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeType target)
   at Caliburn.Micro.View.GetContentPropertyName(Type type)
   at Caliburn.Micro.View.SetContentPropertyCore(Object targetLocation, Object view)
'PVMonitorUWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\loicp\Documents\SourceControl\Sources\PVMonitorUWP\Main\PVMonitorUWP\bin\x64\Debug\AppX\System.IO.Compression.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
WARN:[2016-01-12T10:33:59.3833887+01:00] SetContentProperty failed for ViewLocator.LocateForModel, falling back to LocateForModelType

Regards,

![2016-01-12_103555](https://cloud.githubusercontent.com/assets/11539944/12259821/71903164-b918-11e5-86e7-9cb6531af22a.png)

**Comment by mvermef** [comment]
what was the event you expected and what is the binding to that event within the View in question?  This is usually the result of a datatemplate embedded binding on a click/selection event.

**Comment by lploumen** [comment]
Hi,
There are no events involved in this view...
As I said, this is really strange because same code is working fine on another computer for weeks...
I'll make more tests later and keep you informed.
Thank you,

**Comment by nigel-sampson** [comment]
Could you try using the latest version of the `3.0.0` branch, was running into a different exception in the same method last week and just pushed the fix.

**Comment by rado-r** [comment]
I had similar problem on 10240 Windows build but after update to 10586 problem disappeared.

**Comment by lploumen** [comment]
I had to install the latest W10 sdk and problem seems solved... Although I don't really understand why.

**Comment by nigel-sampson** [comment]
Yeah I'm not 100% sure why the dual SDK's caused this, as far as I can tell this fix resolves it as well.

Closing this out unless it resurfaces for someone.
