### ISSUE TITLE
Caliburn.Micro.Platform - Pdb

### ISSUE THREAD

**Issue by keithdv** [Caliburn-Micro/Caliburn.Micro#303]
Hello,

We're having a very weird issue with our WPF application. Caliburn.Micro.Platform (2.0.1.0) throwing an exception then the application closes. Citrix, Windows Server 2008 R2, .NET Framework 4.5. The issue is on some but not all machines. Only production not QA or Dev of course!

We're confident it's not Caliburn itself but are having a hard time showing that. We're curious what we would see with the Caliburn.Micro.Platform pdb symbols loaded. We've followed the instructions to load symbols from SymbolSource.org. Caliburn.Micro.dll has it's symbols loaded but not Caliburn.Micro.Platform.dll. Looking at the NuSpec files I don't understand why not. 

So:
- Can someone provide the symbols file for Caliburn.Micro.Platform 2.0.1 that correlates with the NuGet package 2.0.1?
- Any ideas why it isn't available on SymbolSource?

Thanks!

Error Stack Trace:

Application: Aon.GRiDS.CS.Portal.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException
Stack:
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Caliburn.Micro.ActionMessage.<.cctor>b__e(Caliburn.Micro.ActionExecutionContext)
   at Caliburn.Micro.ActionMessage.Invoke(System.Object)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(System.Object)
   at System.Windows.Interactivity.EventTriggerBase.OnEvent(System.EventArgs)
   at System.Windows.Interactivity.EventTriggerBase.OnEventImpl(System.Object, System.EventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at System.Windows.Application.Run()
   at Aon.GRiDS.CS.Portal.App.Main()

**Comment by nigel-sampson** [comment]
Apologies, I thought I'd posted a reply to this. I'm not sure why Symbol Source doesn't have the symbols for 2.0.1. They were certainly pushed as part of the release.

You should be able to rebuild the symbols by using the [`v2.0.1`](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/2.0.1) tag.

Let me know if you have any difficulty.
