### ISSUE TITLE
Windows 10 - UWP - "System.InvalidOperationException: 'Sequence contains more than one element'

### ISSUE THREAD

**Issue by wstaelens** [Caliburn-Micro/Caliburn.Micro#491]
> System.InvalidOperationException: 'Sequence contains more than one element'
> 
> 
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
>    at Caliburn.Micro.SimpleContainer.GetInstance(Type service, String key)
>    at Foo.App.GetInstance(Type service, String key)

```csharp
    private readonly IMyService _MyService;
    private readonly IEventAggregator _EventAggregator;

    public OpenFileCommand()
    {
      _MyService = IoC.Get<IMyService>();
      _EventAggregator = IoC.Get<IEventAggregator>(); // <-- crash
    }
```

App.xaml.cs:
```csharp
    protected override void Configure()
    {
      container = new WinRTContainer();
      container.RegisterWinRTServices();
      container.PerRequest<MainViewModel>();
      
      container.RegisterSingleton(typeof(IMyService), null, typeof(MyService));
      container.RegisterSingleton(typeof(IEventAggregator), null, typeof(EventAggregator));
    }
```

**Comment by nigel-sampson** [comment]
`RegisterWinRTServices` registers `IEventAggregator` for you. You can remove your own registration.
