### ISSUE TITLE
TryClose throws Ambiguous match found

### ISSUE THREAD

**Issue by Craigoss** [Caliburn-Micro/Caliburn.Micro#605]
Hello,

We are using version 3.2.0 inconjuction with DevExpress Wpf controls. When we call TryClose from a Screen it throws a "Ambiguous match found" exception. Stack trace below:

Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name)
   at Caliburn.Micro.XamlPlatformProvider.GetViewCloseAction(Object viewModel, ICollection`1 views, Nullable`1 dialogResult)
   at Caliburn.Micro.Screen.TryClose(Nullable`1 dialogResult)

It looks like the issue is in the XamlPlatformProvider.cs in the method GetViewCloseAction. Caliburn micro does a GetMethod("Close"), however DevExpress ThemedWindow has an overloaded Close method aswell as the base Window class. Would it be possible to change this GetMethod() line of code to return GetMethods("Close") and choose the method with no parameters?

Would greatly appreciate an update.

Thanks.

**Comment by nigel-sampson** [comment]
This is definitely something I can add. I doubt I'll do a 3.3 release for it though.

If you're looking for a quicker fix you can inherit from `XamlPlatformProvider` and override `GetViewCloseAction` with the change in it.

**Comment by Craigoss** [comment]
Thanks for the feedback, I have been able to override the class to get it working.
