### ISSUE TITLE
4.0.x alpha bindable collection issue

### ISSUE THREAD

**Issue by Phyxion** [Caliburn-Micro/Caliburn.Micro#698]
If you activate a viewmodel X on the main conductor in `OnViewAttached` and add items to a bindable collection with `Task.Run` in `OnActivateAsync` on X, the `BindableCollection` throws that it cannot modify items on other threads. The workaround I found is to activate X on `OnViewLoaded` instead. In 3.x this worked without problems.

**Comment by nigel-sampson** [comment]
BindableCollection doesn't check threads, can you post the error you're seeing here?

**Comment by Phyxion** [comment]
This is the error. This only happens through `OnViewAttached`, if done in `OnViewLoaded` everything is working fine.

`System.Reflection.TargetInvocationException: 'An error occurred while dispatching a call to the UI Thread'`
`at Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
at Caliburn.Micro.Execute.OnUIThread(Action action)
at Caliburn.Micro.BindableCollection``1.OnUIThread(Action action)
at Caliburn.Micro.BindableCollection``1.ClearItems()
at System.Collections.ObjectModel.Collection``1.Clear()`

In `OnViewAttached` on the main conductor, set `ActiveItem` to a view model. In `OnActivateAsync` of that view model, run something through `Task.Run` and in that clear a `BindableCollection`.
