### ISSUE TITLE
Unable to cast object of type 'ListItem' to type 'System.Collections.Hashtable'

### ISSUE THREAD

**Issue by morfal89** [Caliburn-Micro/Caliburn.Micro#811]
Hi guys,

new here, I got the following error last week and wanted to open the discussion, not sure where this error happened. Do you have any idea/suggestions on how to handle this? Here is the call stack:

Type: System.InvalidCastException
Message: Unable to cast object of type 'ListItem' to type 'System.Collections.Hashtable'.
Source: PresentationCore
HelpLink: 
TargetSite: ListItem getLayoutUpdatedHandler(System.EventHandler)
StackTrace:
    at System.Windows.UIElement.getLayoutUpdatedHandler(EventHandler d)
   at System.Windows.UIElement.remove_LayoutUpdated(EventHandler value)
   at Caliburn.Micro.View.<>c__DisplayClass10_0.<ExecuteOnLayoutUpdated>b__0(Object s, EventArgs e) in D:\a\1\s\src\Caliburn.Micro.Platform\View.cs:line 202
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Tell me if you need more information to understand the issue.
Have a good day

J.

**Comment by vb2ae** [comment]
What are you binding the listview to?
